trigger:
  - main

pr: none

pool:
  name: Default

variables:
  azureServiceConnection: "sc-obs-azure-rg"
  resourceGroupName: "rg-observability-dev"
  acrName: "obsacr11696"
  imageName: "obsapp-v3"
  aciName: "obsapp-v3-aci"
  aciDnsName: "obsappv3-11696"
  location: "westeurope"
  containerPort: "8000"

stages:
- stage: BuildAndDeploy
  displayName: Build, Push and Deploy
  jobs:
  - job: BuildPushDeploy
    displayName: Build image, push to ACR, deploy to ACI
    steps:
    - checkout: self

    - task: AzureCLI@2
      displayName: Deploy to ACI
      inputs:
        azureSubscription: "$(azureServiceConnection)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          set -x

          echo "=== CHECK SUBSCRIPTION ==="
          az account show

          echo "=== LOGIN ACR ==="
          az acr login --name $(acrName)

          IMAGE_TAG=$(Build.BuildId)
          FULL_IMAGE_NAME="$(acrName).azurecr.io/$(imageName):${IMAGE_TAG}"

          echo "IMAGE: $FULL_IMAGE_NAME"
          echo "DNS: $(aciDnsName)"

          echo "=== DELETE OLD CONTAINER (ignore errors) ==="
          az container delete \
            --resource-group $(resourceGroupName) \
            --name $(aciName) \
            --yes || true

          echo "=== CREATE NEW CONTAINER ==="
          az container create \
            --resource-group $(resourceGroupName) \
            --name $(aciName) \
            --image $FULL_IMAGE_NAME \
            --os-type Linux \
            --cpu 1 \
            --memory 1.5 \
            --ports $(containerPort) \
            --ip-address Public \
            --dns-name-label $(aciDnsName) \
            --location $(location) \
            --registry-login-server $(acrName).azurecr.io \
            --registry-username $(acrName) \
            --registry-password $(az acr credential show -n $(acrName) --query "passwords[0].value" -o tsv) \
            --environment-variables PORT=$(containerPort)

          echo "=== GET FQDN ==="
          FQDN=$(az container show \
            --resource-group $(resourceGroupName) \
            --name $(aciName) \
            --query ipAddress.fqdn \
            -o tsv)

          echo "==================================="
          echo "APP URL: http://$FQDN:$(containerPort)"
          echo "==================================="
